[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Future of Publishing: A Look into How Artificial Intelligence is Changing the World of Writing and Publishing"
